/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.58
 * Generated at: 2022-04-27 11:03:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import internet.addBook;
import java.util.ArrayList;

public final class AddBook_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("internet.addBook");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <title>Buchformular</title>\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"http://fonts.googleapis.com/css?family=Bitter\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("      type=\"text/css\"\r\n");
      out.write("    />\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("      .form-style-10 {\r\n");
      out.write("        width: 450px;\r\n");
      out.write("        padding: 30px;\r\n");
      out.write("        margin: 40px auto;\r\n");
      out.write("        background: #fff;\r\n");
      out.write("        border-radius: 10px;\r\n");
      out.write("        -webkit-border-radius: 10px;\r\n");
      out.write("        -moz-border-radius: 10px;\r\n");
      out.write("        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.13);\r\n");
      out.write("        -moz-box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.13);\r\n");
      out.write("        -webkit-box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.13);\r\n");
      out.write("      }\r\n");
      out.write("      .form-style-10 .inner-wrap {\r\n");
      out.write("        padding: 30px;\r\n");
      out.write("        background: #f8f8f8;\r\n");
      out.write("        border-radius: 6px;\r\n");
      out.write("        margin-bottom: 15px;\r\n");
      out.write("      }\r\n");
      out.write("      .form-style-10 h1 {\r\n");
      out.write("        background: #2a88ad;\r\n");
      out.write("        padding: 20px 30px 15px 30px;\r\n");
      out.write("        margin: -30px -30px 30px -30px;\r\n");
      out.write("        border-radius: 10px 10px 0 0;\r\n");
      out.write("        -webkit-border-radius: 10px 10px 0 0;\r\n");
      out.write("        -moz-border-radius: 10px 10px 0 0;\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        text-shadow: 1px 1px 3px rgba(0, 0, 0, 0.12);\r\n");
      out.write("        font: normal 30px \"Bitter\", serif;\r\n");
      out.write("        -moz-box-shadow: inset 0px 2px 2px 0px rgba(255, 255, 255, 0.17);\r\n");
      out.write("        -webkit-box-shadow: inset 0px 2px 2px 0px rgba(255, 255, 255, 0.17);\r\n");
      out.write("        box-shadow: inset 0px 2px 2px 0px rgba(255, 255, 255, 0.17);\r\n");
      out.write("        border: 1px solid #257c9e;\r\n");
      out.write("      }\r\n");
      out.write("      .form-style-10 h1 > span {\r\n");
      out.write("        display: block;\r\n");
      out.write("        margin-top: 2px;\r\n");
      out.write("        font: 13px Arial, Helvetica, sans-serif;\r\n");
      out.write("      }\r\n");
      out.write("      .form-style-10 label {\r\n");
      out.write("        display: block;\r\n");
      out.write("        font: 13px Arial, Helvetica, sans-serif;\r\n");
      out.write("        color: #888;\r\n");
      out.write("        margin-bottom: 15px;\r\n");
      out.write("      }\r\n");
      out.write("      .form-style-10 input[type=\"text\"],\r\n");
      out.write("      .form-style-10 input[type=\"date\"],\r\n");
      out.write("      .form-style-10 input[type=\"datetime\"],\r\n");
      out.write("      .form-style-10 input[type=\"email\"],\r\n");
      out.write("      .form-style-10 input[type=\"number\"],\r\n");
      out.write("      .form-style-10 input[type=\"search\"],\r\n");
      out.write("      .form-style-10 input[type=\"time\"],\r\n");
      out.write("      .form-style-10 input[type=\"url\"],\r\n");
      out.write("      .form-style-10 input[type=\"password\"],\r\n");
      out.write("      .form-style-10 textarea,\r\n");
      out.write("      .form-style-10 select {\r\n");
      out.write("        display: block;\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("        -webkit-box-sizing: border-box;\r\n");
      out.write("        -moz-box-sizing: border-box;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        padding: 8px;\r\n");
      out.write("        border-radius: 6px;\r\n");
      out.write("        -webkit-border-radius: 6px;\r\n");
      out.write("        -moz-border-radius: 6px;\r\n");
      out.write("        border: 2px solid #fff;\r\n");
      out.write("        box-shadow: inset 0px 1px 1px rgba(0, 0, 0, 0.33);\r\n");
      out.write("        -moz-box-shadow: inset 0px 1px 1px rgba(0, 0, 0, 0.33);\r\n");
      out.write("        -webkit-box-shadow: inset 0px 1px 1px rgba(0, 0, 0, 0.33);\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .form-style-10 .section {\r\n");
      out.write("        font: normal 20px \"Bitter\", serif;\r\n");
      out.write("        color: #2a88ad;\r\n");
      out.write("        margin-bottom: 5px;\r\n");
      out.write("      }\r\n");
      out.write("      .form-style-10 .section span {\r\n");
      out.write("        background: #2a88ad;\r\n");
      out.write("        padding: 5px 10px 5px 10px;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        border-radius: 50%;\r\n");
      out.write("        -webkit-border-radius: 50%;\r\n");
      out.write("        -moz-border-radius: 50%;\r\n");
      out.write("        border: 4px solid #fff;\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        margin-left: -45px;\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        margin-top: -3px;\r\n");
      out.write("      }\r\n");
      out.write("      .form-style-10 input[type=\"button\"],\r\n");
      out.write("      .form-style-10 input[type=\"submit\"] {\r\n");
      out.write("        background: #2a88ad;\r\n");
      out.write("        padding: 8px 20px 8px 20px;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        -webkit-border-radius: 5px;\r\n");
      out.write("        -moz-border-radius: 5px;\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        text-shadow: 1px 1px 3px rgba(0, 0, 0, 0.12);\r\n");
      out.write("        font: normal 30px \"Bitter\", serif;\r\n");
      out.write("        -moz-box-shadow: inset 0px 2px 2px 0px rgba(255, 255, 255, 0.17);\r\n");
      out.write("        -webkit-box-shadow: inset 0px 2px 2px 0px rgba(255, 255, 255, 0.17);\r\n");
      out.write("        box-shadow: inset 0px 2px 2px 0px rgba(255, 255, 255, 0.17);\r\n");
      out.write("        border: 1px solid #257c9e;\r\n");
      out.write("        font-size: 15px;\r\n");
      out.write("      }\r\n");
      out.write("      .form-style-10 input[type=\"button\"]:hover,\r\n");
      out.write("      .form-style-10 input[type=\"submit\"]:hover {\r\n");
      out.write("        background: #2a6881;\r\n");
      out.write("        -moz-box-shadow: inset 0px 2px 2px 0px rgba(255, 255, 255, 0.28);\r\n");
      out.write("        -webkit-box-shadow: inset 0px 2px 2px 0px rgba(255, 255, 255, 0.28);\r\n");
      out.write("        box-shadow: inset 0px 2px 2px 0px rgba(255, 255, 255, 0.28);\r\n");
      out.write("      }\r\n");
      out.write("      .form-style-10 .privacy-policy {\r\n");
      out.write("        float: right;\r\n");
      out.write("        width: 250px;\r\n");
      out.write("        font: 12px Arial, Helvetica, sans-serif;\r\n");
      out.write("        color: #4d4d4d;\r\n");
      out.write("        margin-top: 10px;\r\n");
      out.write("        text-align: right;\r\n");
      out.write("      }\r\n");
      out.write("      main {\r\n");
      out.write("        background: linear-gradient(#003471, #448ccb 30%);\r\n");
      out.write("        width: 80%;\r\n");
      out.write("        height: 500px;\r\n");
      out.write("        margin: 10px auto;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      h1 {\r\n");
      out.write("        font-family: Rockwell, Georgia, \"Times New Roman\", Times, serif;\r\n");
      out.write("        font-size: 5em;\r\n");
      out.write("        line-height: 0.5em;\r\n");
      out.write("        margin: 0.3em 0.3em 1em 0.3em;\r\n");
      out.write("        color: #5c82d9;\r\n");
      out.write("        text-shadow: rgba(0, 0, 0, 0.5) -1px 0, rgba(0, 0, 0, 0.3) 0 -1px,\r\n");
      out.write("          rgba(255, 255, 255, 0.5) 2px 2px, rgba(0, 0, 0, 0.3) -1px -2px;\r\n");
      out.write("      }\r\n");
      out.write("      body {\r\n");
      out.write("        background-color: lightblue;\r\n");
      out.write("      }\r\n");
      out.write("    </style>\r\n");
      out.write("    <title>Add a book</title>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <h1>Buchformular</h1>\r\n");
      out.write("    <div class=\"form-style-10\">\r\n");
      out.write("      <h1>\r\n");
      out.write("        buch hinzüfügen<span\r\n");
      out.write("          >bitte die Daten in den feldern richtig eingeben\r\n");
      out.write("        </span>\r\n");
      out.write("      </h1>\r\n");
      out.write("      <form action=\"addBook\" method=\"post\">\r\n");
      out.write("        <div class=\"section\"><span>1</span>title</div>\r\n");
      out.write("        <div class=\"inner-wrap\">\r\n");
      out.write("          <label>title <input type=\"text\" name=\"title\" required /></label>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"section\"><span>2</span> ISBN</div>\r\n");
      out.write("        <div class=\"inner-wrap\">\r\n");
      out.write("          <label> ISBN <input type=\"text\" name=\"ISBN\" required /></label>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"section\"><span>3</span>Preis</div>\r\n");
      out.write("        <div class=\"inner-wrap\">\r\n");
      out.write("          <label>Preis <input type=\"number\" name=\"Price\" required step=\"0.01\"/></label>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"section\"><span>4</span>Autor</div>\r\n");
      out.write("        <div class=\"inner-wrap\">\r\n");
      out.write("          <label>Autor <input type=\"text\" name=\"Author\" required /></label>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"section\"><span>5</span>Describtion</div>\r\n");
      out.write("        <div class=\"inner-wrap\">\r\n");
      out.write("          <label\r\n");
      out.write("            >Describtion <input type=\"text\" name=\"Description\" required\r\n");
      out.write("          /></label>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"section\"><span>6</span>Kategorie/n</div>\r\n");
      out.write("        <div class=\"inner-wrap\">\r\n");
      out.write("    ");
ArrayList<String> std =
        (ArrayList<String>)request.getAttribute("data");
    for(int i =0; i < std.size(); i++){
      out.write("\r\n");
      out.write("            <input type=\"checkbox\" name=");
      out.print(i+1);
      out.write("  />\r\n");
      out.write("            ");
      out.print(std.get(i));
      out.write("\r\n");
      out.write("        ");
}
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"button-section\">\r\n");
      out.write("          <input type=\"submit\" name=\"Sign Up\" />\r\n");
      out.write("        </div>\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
